// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Poodle.Database.Database;

namespace Poodle.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220527131708_Initial5")]
    partial class Initial5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CourseUser", b =>
                {
                    b.Property<int>("CoursesId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("CoursesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("CourseUser");
                });

            modelBuilder.Entity("Poodle.Database.EntityModels.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Public"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Private"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Hidden"
                        });
                });

            modelBuilder.Entity("Poodle.Database.EntityModels.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasFilter("[Title] IS NOT NULL");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "The course gives you a broad range of fundamental knowledge for all IT careers. Through a combination of lecture, hands-on labs, and self-study, you will learn how to install, operate, configure, and verify basic IPv4 and IPv6 networks. The course covers configuring network components such as switches, routers, and wireless LAN controllers; managing network devices; and identifying basic security threats. The course also gives you a foundation in network programmability, automation, and software-defined networking.",
                            Title = "Implementing and Administering Cisco Solutions(CCNA)"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "The course helps you prepare for Cisco DevNet Professional certification and for professional-level network automation engineer roles. You will learn how to implement network applications using Cisco® platforms as a base, from initial software design to diverse system integration, as well as testing and deployment automation. The course gives you hands-on experience solving real world problems using Cisco Application Programming Interfaces (APIs) and modern development tools.",
                            Title = "Developing Applications Using Cisco Core Platforms and APIs (DEVCOR)"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "The course shows you how to deploy, secure, operate, and maintain Cisco Unified Computing System™ (Cisco UCS®) B-series blade servers, Cisco UCS C-Series, and S-Series rack servers for use in data centers. You will learn how to implement management and orchestration software for Cisco UCS. You will gain hands-on practice: configuring key features of Cisco UCS, Cisco UCS Director, and Cisco UCS Manager; implementing UCS management software including Cisco UCS Manager and Cisco Intersight™; and more.",
                            Title = "Configuring Cisco Unified Computing System (DCCUCS)"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "The course shows you how to deploy and manage the Cisco® Nexus® 9000 Series Switches in Cisco Application Centric Infrastructure (Cisco ACI®) mode. You will learn how to configure and manage Cisco Nexus 9000 Series Switches in ACI mode, how to connect the Cisco ACI fabric to external networks and services, and the fundamentals of Virtual Machine Manager (VMM) integration. You will gain hands-on practice implementing key capabilities such as fabric discovery, policies, connectivity, VMM integration, and more.",
                            Title = "Implementing Cisco Application Centric Infrastructure (DCACI)"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "The course shows you how to implement, manage, and troubleshoot Cisco Nexus® 9000 Series Switches in Cisco® NX-OS mode. Through expert instruction and extensive hands-on learning, you will learn how to deploy capabilities including Virtual Extensible LAN (VXLAN), Multiprotocol Label Switching (MPLS), high availability features, Intelligent Traffic Director, troubleshooting tools and techniques, NX-OS programmability features, and open interface technologies.",
                            Title = "Cisco Nexus 9000 Switches in NX-OS Mode"
                        });
                });

            modelBuilder.Entity("Poodle.Database.EntityModels.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Image");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "/Images/DefaultImage.jpg",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "/Images/DefaultImage.jpg",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "/Images/DefaultImage.jpg",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "/Images/DefaultImage.jpg",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "/Images/DefaultImage.jpg",
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "/Images/DefaultImage.jpg",
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "/Images/DefaultImage.jpg",
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "/Images/DefaultImage.jpg",
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "/Images/DefaultImage.jpg",
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "/Images/DefaultImage.jpg",
                            UserId = 10
                        });
                });

            modelBuilder.Entity("Poodle.Database.EntityModels.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Teacher"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Student"
                        });
                });

            modelBuilder.Entity("Poodle.Database.EntityModels.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Title = "Exploring the Functions of Networking"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            Title = "Introducing the Host-to-Host Communications Model"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 1,
                            Title = "Operating Cisco IOS Software"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 2,
                            Title = "Designing for Maintainability"
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 2,
                            Title = "Designing for Serviceability"
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 2,
                            Title = "Describing Advanced REST API Integration"
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 3,
                            Title = "Implementing Cisco UCS Storage Area Network (SAN)"
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 3,
                            Title = "Implementing External Authentication Providers"
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 3,
                            Title = "Describing Cisco UCS Policies for Service Profiles"
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 4,
                            Title = "Ethernet switching products"
                        },
                        new
                        {
                            Id = 11,
                            CourseId = 4,
                            Title = "Data center architecture"
                        },
                        new
                        {
                            Id = 12,
                            CourseId = 4,
                            Title = "Understanding of networking protocols, routing, and switching"
                        },
                        new
                        {
                            Id = 13,
                            CourseId = 5,
                            Title = "Data Center Trends"
                        },
                        new
                        {
                            Id = 14,
                            CourseId = 5,
                            Title = "Describing Cisco Nexus 9000 Series Hardware"
                        },
                        new
                        {
                            Id = 15,
                            CourseId = 5,
                            Title = "Cisco Nexus 9000 NX-OS Features"
                        });
                });

            modelBuilder.Entity("Poodle.Database.EntityModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("ImageId")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Ragnar.Lodbrock@abv.com",
                            FirstName = "Ragnar",
                            ImageId = 1,
                            LastName = "Lodbrock",
                            Password = "adminADMIN123?",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "Jack.Richmond@yahoo.com",
                            FirstName = "Jack",
                            ImageId = 2,
                            LastName = "Richmond",
                            Password = "johnJOHN123!",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "Jonathan.Davis@gmail.com",
                            FirstName = "Jonathan",
                            ImageId = 3,
                            LastName = "Davis",
                            Password = "jondav123*",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 4,
                            Email = "Ignatio.Italiano@gmail.com",
                            FirstName = "Ignatio",
                            ImageId = 4,
                            LastName = "Italiano",
                            Password = "ignitalo123*",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 5,
                            Email = "Reginald.Hargreeves@gmail.com",
                            FirstName = "Reginald",
                            ImageId = 5,
                            LastName = "Hargreeves",
                            Password = "jamesonN123*",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 6,
                            Email = "John.Hanes@gmail.com",
                            FirstName = "John",
                            ImageId = 6,
                            LastName = "Hanes",
                            Password = "johnsonN123*",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 7,
                            Email = "Horatio.Spanish@gmail.com",
                            FirstName = "Horatio",
                            ImageId = 7,
                            LastName = "Spanish",
                            Password = "horspanP123*",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 8,
                            Email = "Herbert.Spencer@gmail.com",
                            FirstName = "Herbert",
                            ImageId = 8,
                            LastName = "Spencer",
                            Password = "hurspenM456!",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 9,
                            Email = "Harriet.Dark@gmail.com",
                            FirstName = "Harriet",
                            ImageId = 9,
                            LastName = "Dark",
                            Password = "hardiR789*",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 10,
                            Email = "Mario.Caruso@gmail.com",
                            FirstName = "Mario",
                            ImageId = 10,
                            LastName = "Caruso",
                            Password = "marrob123!",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("CourseUser", b =>
                {
                    b.HasOne("Poodle.Database.EntityModels.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poodle.Database.EntityModels.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Poodle.Database.EntityModels.Course", b =>
                {
                    b.HasOne("Poodle.Database.EntityModels.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Poodle.Database.EntityModels.Section", b =>
                {
                    b.HasOne("Poodle.Database.EntityModels.Course", "Course")
                        .WithMany("Sections")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Poodle.Database.EntityModels.User", b =>
                {
                    b.HasOne("Poodle.Database.EntityModels.Image", "Image")
                        .WithOne("User")
                        .HasForeignKey("Poodle.Database.EntityModels.User", "ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poodle.Database.EntityModels.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Poodle.Database.EntityModels.Course", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Poodle.Database.EntityModels.Image", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Poodle.Database.EntityModels.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
