// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Poodle.Data;

namespace Poodle.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220615062857_New15June")]
    partial class New15June
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CourseUser", b =>
                {
                    b.Property<int>("CoursesId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("CoursesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("CourseUser");
                });

            modelBuilder.Entity("Poodle.Data.EntityModels.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Public"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Private"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Restricted"
                        });
                });

            modelBuilder.Entity("Poodle.Data.EntityModels.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhotoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasFilter("[Title] IS NOT NULL");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2022, 6, 15, 6, 28, 56, 580, DateTimeKind.Utc).AddTicks(3924),
                            Description = "The course gives you a broad range of fundamental knowledge for all IT careers. Through a combination of lecture, hands-on labs, and self-study, you will learn how to install, operate, configure, and verify basic IPv4 and IPv6 networks. The course covers configuring network components such as switches, routers, and wireless LAN controllers; managing network devices; and identifying basic security threats. The course also gives you a foundation in network programmability, automation, and software-defined networking.",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 6, 15, 6, 28, 56, 580, DateTimeKind.Utc).AddTicks(3930),
                            PhotoURL = "img/course-1.jpg",
                            Title = "Implementing and Administering Solutions(CCNA)"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2022, 6, 15, 6, 28, 56, 580, DateTimeKind.Utc).AddTicks(3969),
                            Description = "The course helps you prepare for DevNet Professional certification and for professional-level network automation engineer roles. You will learn how to implement network applications using Cisco® platforms as a base, from initial software design to diverse system integration, as well as testing and deployment automation. The course gives you hands-on experience solving real world problems using Cisco Application Programming Interfaces (APIs) and modern development tools.",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 6, 15, 6, 28, 56, 580, DateTimeKind.Utc).AddTicks(3971),
                            PhotoURL = "img/course-2.jpg",
                            Title = "Developing Applications Using Core Platforms and APIs (DEVCOR)"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2022, 6, 15, 6, 28, 56, 580, DateTimeKind.Utc).AddTicks(3974),
                            Description = "The course shows you how to deploy, secure, operate, and maintain Unified Computing System™ (Cisco UCS®) B-series blade servers, Cisco UCS C-Series, and S-Series rack servers for use in data centers. You will learn how to implement management and orchestration software for Cisco UCS. You will gain hands-on practice: configuring key features of Cisco UCS, Cisco UCS Director, and Cisco UCS Manager; implementing UCS management software including Cisco UCS Manager and Cisco Intersight™; and more.",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 6, 15, 6, 28, 56, 580, DateTimeKind.Utc).AddTicks(3976),
                            PhotoURL = "img/course-3.jpg",
                            Title = "Configuring Unified Computing System (DCCUCS)"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2022, 6, 15, 6, 28, 56, 580, DateTimeKind.Utc).AddTicks(3979),
                            Description = "The course shows you how to deploy and manage the  Nexus® 9000 Series Switches in Cisco Application Centric Infrastructure (Cisco ACI®) mode. You will learn how to configure and manage Cisco Nexus 9000 Series Switches in ACI mode, how to connect the Cisco ACI fabric to external networks and services, and the fundamentals of Virtual Machine Manager (VMM) integration. You will gain hands-on practice implementing key capabilities such as fabric discovery, policies, connectivity, VMM integration, and more.",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 6, 15, 6, 28, 56, 580, DateTimeKind.Utc).AddTicks(3980),
                            PhotoURL = "img/course-4.jpg",
                            Title = "Implementing Application Centric Infrastructure (DCACI)"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2022, 6, 15, 6, 28, 56, 580, DateTimeKind.Utc).AddTicks(3983),
                            Description = "The course shows you how to implement, manage, and troubleshoot  Nexus® 9000 Series Switches in Cisco® NX-OS mode. Through expert instruction and extensive hands-on learning, you will learn how to deploy capabilities including Virtual Extensible LAN (VXLAN), Multiprotocol Label Switching (MPLS), high availability features, Intelligent Traffic Director, troubleshooting tools and techniques, NX-OS programmability features, and open interface technologies.",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 6, 15, 6, 28, 56, 580, DateTimeKind.Utc).AddTicks(3984),
                            PhotoURL = "img/course-5.jpg",
                            Title = "Nexus 9000 Switches in NX-OS Mode"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2022, 6, 15, 6, 28, 56, 580, DateTimeKind.Utc).AddTicks(3991),
                            Description = "The course, Mulitcloud Automation and Orchestration with  CloudCenter Suite (CLDAO) v1.0 teaches you how to configure simplified orchestration and workflow automation that provides seamless integration within the Cisco® CloudCenter suite. Through lessons and hands-on experiences, you will learn to use the tools of the CloudCenter Suite to streamline business processes, automate tasks, and increase efficiency in business processes.",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 6, 15, 6, 28, 56, 580, DateTimeKind.Utc).AddTicks(3993),
                            PhotoURL = "img/course-6.jpg",
                            Title = "Multicloud Automation and Orchestration with CloudCenter Suite (CLDAO) 1.0"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2022, 6, 15, 6, 28, 56, 580, DateTimeKind.Utc).AddTicks(3996),
                            Description = "A Guided Study Group offers you a 180-day journey of certification preparation. This approach offers a best-of-all-worlds path toward certification, with the flexibility and convenience of e-learning plus the motivation and accountability of working with a live coach. A mix of participants from various backgrounds and skill levels encourages collaboration.",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 6, 15, 6, 28, 56, 580, DateTimeKind.Utc).AddTicks(3997),
                            PhotoURL = "img/course-7.jpg",
                            Title = "Guided Study Group - CyberOps (GSG-CBROPS) 1.0"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2022, 6, 15, 6, 28, 56, 580, DateTimeKind.Utc).AddTicks(4000),
                            Description = "Through a combination of lessons and hands-on learning, you will practice operating, managing, and integrating Cisco DNA Center, programmable network infrastructure, and Cisco SD-Access fundamentals. You will learn how Cisco delivers intent-based networking across the campus, branch, WAN, and extended enterprise and ensures that your network is operating as intended.",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 6, 15, 6, 28, 56, 580, DateTimeKind.Utc).AddTicks(4001),
                            PhotoURL = "img/course-8.jpg",
                            Title = "Transforming to a Intent Based Network (IBNTRN) 1.0"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2022, 6, 15, 6, 28, 56, 580, DateTimeKind.Utc).AddTicks(4004),
                            Description = "In this module, you'll learn how to take advantage of several virtualization services in Azure compute, which can help your applications scale out quickly and efficiently to meet increasing demands.",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 6, 15, 6, 28, 56, 580, DateTimeKind.Utc).AddTicks(4005),
                            PhotoURL = "img/course-9.jpg",
                            Title = "Microsoft Azure Fundamentals: Describe core Azure services"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2022, 6, 15, 6, 28, 56, 580, DateTimeKind.Utc).AddTicks(4010),
                            Description = "Create a basic GitHub Action and use that action in a workflow.",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 6, 15, 6, 28, 56, 580, DateTimeKind.Utc).AddTicks(4012),
                            PhotoURL = "img/course-10.jpg",
                            Title = "Automate development tasks by using GitHub Actions"
                        });
                });

            modelBuilder.Entity("Poodle.Data.EntityModels.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "/img/DefaultImage.jpg",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "/img/DefaultImage.jpg",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "/img/DefaultImage.jpg",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "/img/DefaultImage.jpg",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "/img/DefaultImage.jpg",
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "/img/DefaultImage.jpg",
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "/img/DefaultImage.jpg",
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "/img/DefaultImage.jpg",
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "/img/DefaultImage.jpg",
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "/img/DefaultImage.jpg",
                            UserId = 10
                        });
                });

            modelBuilder.Entity("Poodle.Data.EntityModels.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Teacher"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Student"
                        });
                });

            modelBuilder.Entity("Poodle.Data.EntityModels.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmbeded")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRestricted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "testTest",
                            CourseId = 1,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsEmbeded = false,
                            IsRestricted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rank = 1,
                            Title = "Exploring the Functions of Networking"
                        },
                        new
                        {
                            Id = 2,
                            Content = "testTest",
                            CourseId = 1,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsEmbeded = false,
                            IsRestricted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rank = 2,
                            Title = "Introducing the Host-to-Host Communications Model"
                        },
                        new
                        {
                            Id = 3,
                            Content = "testTest",
                            CourseId = 1,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsEmbeded = false,
                            IsRestricted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rank = 3,
                            Title = "Operating Cisco IOS Software"
                        },
                        new
                        {
                            Id = 4,
                            Content = "testTest",
                            CourseId = 2,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsEmbeded = false,
                            IsRestricted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rank = 1,
                            Title = "Designing for Maintainability"
                        },
                        new
                        {
                            Id = 5,
                            Content = "testTest",
                            CourseId = 2,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsEmbeded = false,
                            IsRestricted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rank = 2,
                            Title = "Designing for Serviceability"
                        },
                        new
                        {
                            Id = 6,
                            Content = "testTest",
                            CourseId = 2,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsEmbeded = false,
                            IsRestricted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rank = 3,
                            Title = "Describing Advanced REST API Integration"
                        },
                        new
                        {
                            Id = 7,
                            Content = "testTest",
                            CourseId = 3,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsEmbeded = false,
                            IsRestricted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rank = 1,
                            Title = "Implementing Cisco UCS Storage Area Network (SAN)"
                        },
                        new
                        {
                            Id = 8,
                            Content = "testTest",
                            CourseId = 3,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsEmbeded = false,
                            IsRestricted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rank = 2,
                            Title = "Implementing External Authentication Providers"
                        },
                        new
                        {
                            Id = 9,
                            Content = "testTest",
                            CourseId = 3,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsEmbeded = false,
                            IsRestricted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rank = 3,
                            Title = "Describing Cisco UCS Policies for Service Profiles"
                        },
                        new
                        {
                            Id = 10,
                            Content = "testTest",
                            CourseId = 4,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsEmbeded = false,
                            IsRestricted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rank = 1,
                            Title = "Ethernet switching products"
                        },
                        new
                        {
                            Id = 11,
                            Content = "testTest",
                            CourseId = 4,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsEmbeded = false,
                            IsRestricted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rank = 2,
                            Title = "Data center architecture"
                        },
                        new
                        {
                            Id = 12,
                            Content = "testTest",
                            CourseId = 4,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsEmbeded = false,
                            IsRestricted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rank = 3,
                            Title = "Understanding of networking protocols, routing, and switching"
                        },
                        new
                        {
                            Id = 13,
                            Content = "testTest",
                            CourseId = 5,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsEmbeded = false,
                            IsRestricted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rank = 1,
                            Title = "Data Center Trends"
                        },
                        new
                        {
                            Id = 14,
                            Content = "testTest",
                            CourseId = 5,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsEmbeded = false,
                            IsRestricted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rank = 2,
                            Title = "Describing Nexus 9000 Series Hardware"
                        },
                        new
                        {
                            Id = 15,
                            Content = "testTest",
                            CourseId = 5,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsEmbeded = false,
                            IsRestricted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rank = 3,
                            Title = "Nexus 9000 NX-OS Features"
                        },
                        new
                        {
                            Id = 16,
                            Content = "testTest",
                            CourseId = 6,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsEmbeded = false,
                            IsRestricted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rank = 1,
                            Title = "Introducing CloudCenter Suite Action Orchestrator"
                        },
                        new
                        {
                            Id = 17,
                            Content = "testTest",
                            CourseId = 6,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsEmbeded = false,
                            IsRestricted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rank = 2,
                            Title = "CloudCenter Suite Architecture"
                        },
                        new
                        {
                            Id = 18,
                            Content = "testTest",
                            CourseId = 6,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsEmbeded = false,
                            IsRestricted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rank = 3,
                            Title = "Defining Action Orchestrator User Management and Security Considerations"
                        },
                        new
                        {
                            Id = 19,
                            Content = "testTest",
                            CourseId = 7,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsEmbeded = false,
                            IsRestricted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rank = 1,
                            Title = "Identifying Security Concepts"
                        },
                        new
                        {
                            Id = 20,
                            Content = "testTest",
                            CourseId = 7,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsEmbeded = false,
                            IsRestricted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rank = 2,
                            Title = "Defining the Security Operations Center"
                        },
                        new
                        {
                            Id = 21,
                            Content = "testTest",
                            CourseId = 7,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsEmbeded = false,
                            IsRestricted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rank = 3,
                            Title = "SOC Analyst tools"
                        },
                        new
                        {
                            Id = 22,
                            Content = "testTest",
                            CourseId = 8,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsEmbeded = false,
                            IsRestricted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rank = 1,
                            Title = "Introducing DNA Architecture"
                        },
                        new
                        {
                            Id = 23,
                            Content = "testTest",
                            CourseId = 8,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsEmbeded = false,
                            IsRestricted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rank = 2,
                            Title = "Deploy Wired Fabric Networks with DNA Center"
                        },
                        new
                        {
                            Id = 24,
                            Content = "testTest",
                            CourseId = 8,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsEmbeded = false,
                            IsRestricted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rank = 3,
                            Title = "Deploy Brownfield and Fabric Wireless Network with DNA Center"
                        },
                        new
                        {
                            Id = 25,
                            Content = "testTest",
                            CourseId = 9,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsEmbeded = false,
                            IsRestricted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rank = 1,
                            Title = "Introduction"
                        },
                        new
                        {
                            Id = 26,
                            Content = "testTest",
                            CourseId = 9,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsEmbeded = false,
                            IsRestricted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rank = 2,
                            Title = "Overview of Azure compute services"
                        },
                        new
                        {
                            Id = 27,
                            Content = "testTest",
                            CourseId = 9,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsEmbeded = false,
                            IsRestricted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rank = 3,
                            Title = "Decide when to use Azure Virtual Machines"
                        },
                        new
                        {
                            Id = 28,
                            Content = "testTest",
                            CourseId = 10,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsEmbeded = false,
                            IsRestricted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rank = 1,
                            Title = "Introduction"
                        },
                        new
                        {
                            Id = 29,
                            Content = "testTest",
                            CourseId = 10,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsEmbeded = false,
                            IsRestricted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rank = 2,
                            Title = "How does GitHub Actions automate development tasks?"
                        },
                        new
                        {
                            Id = 30,
                            Content = "testTest",
                            CourseId = 10,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsEmbeded = false,
                            IsRestricted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rank = 3,
                            Title = "Identify the components of GitHub Actions"
                        });
                });

            modelBuilder.Entity("Poodle.Data.EntityModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("ImageId")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2022, 6, 15, 6, 28, 56, 578, DateTimeKind.Utc).AddTicks(7167),
                            Email = "Ragnar.Lodbrock@abv.com",
                            FirstName = "Ragnar",
                            ImageId = 1,
                            IsDeleted = false,
                            LastName = "Lodbrock",
                            ModifiedOn = new DateTime(2022, 6, 15, 6, 28, 56, 578, DateTimeKind.Utc).AddTicks(7690),
                            Password = "adminADMIN123?",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2022, 6, 15, 6, 28, 56, 578, DateTimeKind.Utc).AddTicks(8814),
                            Email = "Jack.Richmond@yahoo.com",
                            FirstName = "Jack",
                            ImageId = 2,
                            IsDeleted = false,
                            LastName = "Richmond",
                            ModifiedOn = new DateTime(2022, 6, 15, 6, 28, 56, 578, DateTimeKind.Utc).AddTicks(8819),
                            Password = "johnJOHN123!",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2022, 6, 15, 6, 28, 56, 578, DateTimeKind.Utc).AddTicks(8823),
                            Email = "Jonathan.Davis@gmail.com",
                            FirstName = "Jonathan",
                            ImageId = 3,
                            IsDeleted = false,
                            LastName = "Davis",
                            ModifiedOn = new DateTime(2022, 6, 15, 6, 28, 56, 578, DateTimeKind.Utc).AddTicks(8824),
                            Password = "jondav123*",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2022, 6, 15, 6, 28, 56, 578, DateTimeKind.Utc).AddTicks(8828),
                            Email = "Ignatio.Italiano@gmail.com",
                            FirstName = "Ignatio",
                            ImageId = 4,
                            IsDeleted = false,
                            LastName = "Italiano",
                            ModifiedOn = new DateTime(2022, 6, 15, 6, 28, 56, 578, DateTimeKind.Utc).AddTicks(8830),
                            Password = "ignitalo123*",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2022, 6, 15, 6, 28, 56, 578, DateTimeKind.Utc).AddTicks(8832),
                            Email = "Reginald.Hargreeves@gmail.com",
                            FirstName = "Reginald",
                            ImageId = 5,
                            IsDeleted = false,
                            LastName = "Hargreeves",
                            ModifiedOn = new DateTime(2022, 6, 15, 6, 28, 56, 578, DateTimeKind.Utc).AddTicks(8834),
                            Password = "jamesonN123*",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2022, 6, 15, 6, 28, 56, 578, DateTimeKind.Utc).AddTicks(8844),
                            Email = "John.Hanes@gmail.com",
                            FirstName = "John",
                            ImageId = 6,
                            IsDeleted = false,
                            LastName = "Hanes",
                            ModifiedOn = new DateTime(2022, 6, 15, 6, 28, 56, 578, DateTimeKind.Utc).AddTicks(8845),
                            Password = "johnsonN123*",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2022, 6, 15, 6, 28, 56, 578, DateTimeKind.Utc).AddTicks(8848),
                            Email = "Horatio.Spanish@gmail.com",
                            FirstName = "Horatio",
                            ImageId = 7,
                            IsDeleted = false,
                            LastName = "Spanish",
                            ModifiedOn = new DateTime(2022, 6, 15, 6, 28, 56, 578, DateTimeKind.Utc).AddTicks(8849),
                            Password = "horspanP123*",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2022, 6, 15, 6, 28, 56, 578, DateTimeKind.Utc).AddTicks(8852),
                            Email = "Herbert.Spencer@gmail.com",
                            FirstName = "Herbert",
                            ImageId = 8,
                            IsDeleted = false,
                            LastName = "Spencer",
                            ModifiedOn = new DateTime(2022, 6, 15, 6, 28, 56, 578, DateTimeKind.Utc).AddTicks(8854),
                            Password = "hurspenM456!",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2022, 6, 15, 6, 28, 56, 578, DateTimeKind.Utc).AddTicks(8857),
                            Email = "Harriet.Dark@gmail.com",
                            FirstName = "Harriet",
                            ImageId = 9,
                            IsDeleted = false,
                            LastName = "Dark",
                            ModifiedOn = new DateTime(2022, 6, 15, 6, 28, 56, 578, DateTimeKind.Utc).AddTicks(8858),
                            Password = "hardiR789*",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2022, 6, 15, 6, 28, 56, 578, DateTimeKind.Utc).AddTicks(8863),
                            Email = "Mario.Caruso@gmail.com",
                            FirstName = "Mario",
                            ImageId = 10,
                            IsDeleted = false,
                            LastName = "Caruso",
                            ModifiedOn = new DateTime(2022, 6, 15, 6, 28, 56, 578, DateTimeKind.Utc).AddTicks(8864),
                            Password = "marrob123!",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("CourseUser", b =>
                {
                    b.HasOne("Poodle.Data.EntityModels.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poodle.Data.EntityModels.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Poodle.Data.EntityModels.Course", b =>
                {
                    b.HasOne("Poodle.Data.EntityModels.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Poodle.Data.EntityModels.Section", b =>
                {
                    b.HasOne("Poodle.Data.EntityModels.Course", "Course")
                        .WithMany("Sections")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Poodle.Data.EntityModels.User", b =>
                {
                    b.HasOne("Poodle.Data.EntityModels.Image", "Image")
                        .WithOne("User")
                        .HasForeignKey("Poodle.Data.EntityModels.User", "ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poodle.Data.EntityModels.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Poodle.Data.EntityModels.Course", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Poodle.Data.EntityModels.Image", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Poodle.Data.EntityModels.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
